config/routes.rb
Rails.application.routes.draw do
  get 'faktury/index'

  resources :klients

  resources :kontos

  resources :fakturas

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'faktury#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/faktura.rb
class Faktura < ActiveRecord::Base
  belongs_to :klient
end

app/models/klient.rb
class Klient < ActiveRecord::Base
  has_many :kontos
  has_many :fakturas
end

app/models/konto.rb
class Konto < ActiveRecord::Base
  belongs_to :klient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fakturas_controller.rb
class FakturasController < ApplicationController
  before_action :set_faktura, only: [:show, :edit, :update, :destroy]

  # GET /fakturas
  # GET /fakturas.json
  def index
    @fakturas = Faktura.all
  end

  # GET /fakturas/1
  # GET /fakturas/1.json
  def show
  end

  # GET /fakturas/new
  def new
    @faktura = Faktura.new
  end

  # GET /fakturas/1/edit
  def edit
  end

  # POST /fakturas
  # POST /fakturas.json
  def create
    @faktura = Faktura.new(faktura_params)

    respond_to do |format|
      if @faktura.save
        format.html { redirect_to @faktura, notice: 'Faktura was successfully created.' }
        format.json { render :show, status: :created, location: @faktura }
      else
        format.html { render :new }
        format.json { render json: @faktura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fakturas/1
  # PATCH/PUT /fakturas/1.json
  def update
    respond_to do |format|
      if @faktura.update(faktura_params)
        format.html { redirect_to @faktura, notice: 'Faktura was successfully updated.' }
        format.json { render :show, status: :ok, location: @faktura }
      else
        format.html { render :edit }
        format.json { render json: @faktura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fakturas/1
  # DELETE /fakturas/1.json
  def destroy
    @faktura.destroy
    respond_to do |format|
      format.html { redirect_to fakturas_url, notice: 'Faktura was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faktura
      @faktura = Faktura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faktura_params
      params.require(:faktura).permit(:id, :tytul, :data, :wyslana, :klient_id)
    end
end

app/controllers/faktury_controller.rb
class FakturyController < ApplicationController
  def index
  end
end

app/controllers/klients_controller.rb
class KlientsController < ApplicationController
  before_action :set_klient, only: [:show, :edit, :update, :destroy]

  # GET /klients
  # GET /klients.json
  def index
    @klients = Klient.all
  end

  # GET /klients/1
  # GET /klients/1.json
  def show
  end

  # GET /klients/new
  def new
    @klient = Klient.new
  end

  # GET /klients/1/edit
  def edit
  end

  # POST /klients
  # POST /klients.json
  def create
    @klient = Klient.new(klient_params)

    respond_to do |format|
      if @klient.save
        format.html { redirect_to @klient, notice: 'Klient was successfully created.' }
        format.json { render :show, status: :created, location: @klient }
      else
        format.html { render :new }
        format.json { render json: @klient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /klients/1
  # PATCH/PUT /klients/1.json
  def update
    respond_to do |format|
      if @klient.update(klient_params)
        format.html { redirect_to @klient, notice: 'Klient was successfully updated.' }
        format.json { render :show, status: :ok, location: @klient }
      else
        format.html { render :edit }
        format.json { render json: @klient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /klients/1
  # DELETE /klients/1.json
  def destroy
    @klient.destroy
    respond_to do |format|
      format.html { redirect_to klients_url, notice: 'Klient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_klient
      @klient = Klient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def klient_params
      params.require(:klient).permit(:imie, :nazwisko, :kid, :blad, :id)
    end
end

app/controllers/kontos_controller.rb
class KontosController < ApplicationController
  before_action :set_konto, only: [:show, :edit, :update, :destroy]

  # GET /kontos
  # GET /kontos.json
  def index
    @kontos = Konto.all
  end

  # GET /kontos/1
  # GET /kontos/1.json
  def show
  end

  # GET /kontos/new
  def new
    @konto = Konto.new
  end

  # GET /kontos/1/edit
  def edit
  end

  # POST /kontos
  # POST /kontos.json
  def create
    @konto = Konto.new(konto_params)

    respond_to do |format|
      if @konto.save
        format.html { redirect_to @konto, notice: 'Konto was successfully created.' }
        format.json { render :show, status: :created, location: @konto }
      else
        format.html { render :new }
        format.json { render json: @konto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kontos/1
  # PATCH/PUT /kontos/1.json
  def update
    respond_to do |format|
      if @konto.update(konto_params)
        format.html { redirect_to @konto, notice: 'Konto was successfully updated.' }
        format.json { render :show, status: :ok, location: @konto }
      else
        format.html { render :edit }
        format.json { render json: @konto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kontos/1
  # DELETE /kontos/1.json
  def destroy
    @konto.destroy
    respond_to do |format|
      format.html { redirect_to kontos_url, notice: 'Konto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_konto
      @konto = Konto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def konto_params
      params.require(:konto).permit(:id, :konto, :klient_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fakturas_helper.rb
module FakturasHelper
end

app/helpers/faktury_helper.rb
module FakturyHelper
end

app/helpers/klients_helper.rb
module KlientsHelper
end

app/helpers/kontos_helper.rb
module KontosHelper
end

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/fakturas/_form.html.erb
<%= form_for @faktura, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :id, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :id, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tytul, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :tytul, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :data, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.date_select :data, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :wyslana, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :wyslana, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  fakturas_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/fakturas/edit.html.erb
<%- model_class = Faktura -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Faktura %></h1>
</div>
<%= render :partial => 'form' %>

app/views/fakturas/index.html.erb
<%- model_class = Faktura -%>
<div class="page-header">
  <h1><%=t '.title', :default => Faktura %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:tytul) %></th>
      <th><%= model_class.human_attribute_name(:data) %></th>
      <th><%= model_class.human_attribute_name(:wyslana) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @fakturas.each do |faktura| %>
      <tr>
        <td><%= faktura.id %></td>
        <td><%= faktura.id %></td>
        <td><%= faktura.tytul %></td>
        <td><%= faktura.data %></td>
        <td><%= faktura.wyslana %></td>
        <td><%=l faktura.created_at, format: :long %></td>
        <td>
          <%= link_to faktura_path(faktura), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to faktura_path(faktura), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_faktura_path,
            :class => 'btn btn-primary' %>

app/views/fakturas/new.html.erb
<%- model_class = Faktura -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Faktura %></h1>
</div>
<%= render :partial => 'form' %>

app/views/fakturas/show.html.erb
<%- model_class = Faktura -%>
<div class="page-header">
  <h1><%=t '.title', :default => Faktura %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:id) %></dt>
      <dd><pre class="prettyprint"><%= @faktura.id %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:tytul) %></dt>
      <dd><pre class="prettyprint"><%= @faktura.tytul %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:data) %></dt>
      <dd><pre class="prettyprint"><%= @faktura.data %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:wyslana) %></dt>
      <dd><pre class="prettyprint"><%= @faktura.wyslana %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              fakturas_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_faktura_path(@faktura), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              faktura_path(@faktura),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/faktury/index.html.erb
<h1>Faktury#index</h1>
<p>Find me in app/views/faktury/index.html.erb</p>

app/views/klients/_form.html.erb
<%= form_for @klient, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :imie, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :imie, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nazwisko, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :nazwisko, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :kid, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :kid, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :blad, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :blad, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :id, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :id, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  klients_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/klients/edit.html.erb
<%- model_class = Klient -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Klient %></h1>
</div>
<%= render :partial => 'form' %>

app/views/klients/index.html.erb
<%- model_class = Klient -%>
<div class="page-header">
  <h1><%=t '.title', :default => Klient %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:imie) %></th>
      <th><%= model_class.human_attribute_name(:nazwisko) %></th>
      <th><%= model_class.human_attribute_name(:kid) %></th>
      <th><%= model_class.human_attribute_name(:blad) %></th>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @klients.each do |klient| %>
      <tr>
        <td><%= klient.id %></td>
        <td><%= klient.imie %></td>
        <td><%= klient.nazwisko %></td>
        <td><%= klient.kid %></td>
        <td><%= klient.blad %></td>
        <td><%= klient.id %></td>
        <td><%=l klient.created_at, format: :long %></td>
        <td>
          <%= link_to klient_path(klient), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to klient_path(klient), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_klient_path,
            :class => 'btn btn-primary' %>

app/views/klients/new.html.erb
<%- model_class = Klient -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Klient %></h1>
</div>
<%= render :partial => 'form' %>

app/views/klients/show.html.erb
<%- model_class = Klient -%>
<div class="page-header">
  <h1><%=t '.title', :default => Klient %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:imie) %></dt>
      <dd><pre class="prettyprint"><%= @klient.imie %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:nazwisko) %></dt>
      <dd><pre class="prettyprint"><%= @klient.nazwisko %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:kid) %></dt>
      <dd><pre class="prettyprint"><%= @klient.kid %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:blad) %></dt>
      <dd><pre class="prettyprint"><%= @klient.blad %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:id) %></dt>
      <dd><pre class="prettyprint"><%= @klient.id %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              klients_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_klient_path(@klient), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              klient_path(@klient),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/kontos/_form.html.erb
<%= form_for @konto, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :id, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :id, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :konto, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :konto, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  kontos_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/kontos/edit.html.erb
<%- model_class = Konto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Konto %></h1>
</div>
<%= render :partial => 'form' %>

app/views/kontos/index.html.erb
<%- model_class = Konto -%>
<div class="page-header">
  <h1><%=t '.title', :default => Konto %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:konto) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @kontos.each do |konto| %>
      <tr>
        <td><%= konto.id %></td>
        <td><%= konto.id %></td>
        <td><%= konto.konto %></td>
        <td><%=l konto.created_at, format: :long %></td>
        <td>
          <%= link_to konto_path(konto), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to konto_path(konto), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_konto_path,
            :class => 'btn btn-primary' %>

app/views/kontos/new.html.erb
<%- model_class = Konto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Konto %></h1>
</div>
<%= render :partial => 'form' %>

app/views/kontos/show.html.erb
<%- model_class = Konto -%>
<div class="page-header">
  <h1><%=t '.title', :default => Konto %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:id) %></dt>
      <dd><pre class="prettyprint"><%= @konto.id %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:konto) %></dt>
      <dd><pre class="prettyprint"><%= @konto.konto %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              kontos_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_konto_path(@konto), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              konto_path(@konto),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CareworkRuby</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>